#!/bin/bash

# purpose: install clpm2

BIN=$HOME/bin
CLPM=$HOME/clpm2

cd $BIN &&
cp $CLPM/p . &&
echo copied p &&
cp $CLPM/f . &&
echo copied f &&
cp $CLPM/_p . &&
echo copied _p &&
ln -f _p _f &&
echo linked _f &&
ln -f _p fa &&
echo linked fa &&
ln -f _p x &&
echo linked x &&
ln -f _p xa &&
echo linked xa &&
ln -f _p z &&
echo linked z &&
ln -f _p zdir &&
echo linked zdir &&
cp $CLPM/af . &&
echo copied af &&
cp $CLPM/d . &&
echo copied d &&
chmod 700 p _p f _f fa x xa z zdir af d &&
echo chmod 700

cat <<'EOF'

NOTE: Add the following lines to your .bash_profile

alias d='. d'
alias f='. f'
alias p='. p'
alias af='. af'
source ~/.penv
export AF_DIR=$HOME # or whatever

EOF
